routes/web.php
Route::namespace('Portal')->name('portal.')->group(function() {
	Route::any('/portal/login', 'PortalController@login')->name('login_portal');
	Route::any('/portal/senha', 'PortalController@alterarSenha')->name('alterar_senha_portal');
	Route::middleware('portal')->group(function() {
		Route::get('/portal', 'PortalController@grid')->name('grid_portal');
		Route::any('/portal/logout', 'PortalController@logout')->name('logout_portal');
		Route::get('/portal/dados_pedido/{pedido?}', 'PortalController@dadosPedido')->name('dados_pedido_portal');
	});
});

Route::middleware('auth')->namespace('Configuracao')->name('configuracao.')->group(function () {
	Route::get('/configuracao/lista_tratativas', 'ConfiguracaoController@listaTratativas')->name('lista_tratativas');
	Route::any('/configuracao/editar_tratativa/{id?}', 'ConfiguracaoController@editarTratativa')->name('editar_tratativa');
	Route::get('/configuracao/lista_acoes', 'ConfiguracaoController@listaAcoes')->name('lista_acoes');
	Route::any('/configuracao/editar_acao/{id?}', 'ConfiguracaoController@editarAcao')->name('editar_acao');
	Route::get('/configuracao/lista_condicoes_especiais', 'ConfiguracaoController@listaCondicoesEspeciais')->name('lista_condicoes_especiais');
	Route::any('/configuracao/editar_condicao_especial/{id?}', 'ConfiguracaoController@editarCondicaoEspecial')->name('editar_condicao_especial');
	Route::get('/configuracao/lista_campos', 'ConfiguracaoController@listaCampos')->name('lista_campos');
	Route::any('/configuracao/editar_campo/{id?}', 'ConfiguracaoController@editarCampo')->name('editar_campo');

	Route::any('/configuracao', 'ConfiguracaoController@exibir')->name('tratativas_automaticas');
	Route::any('/configuracao/historico', 'ConfiguracaoController@exibirHistorico')->name('historico');
	Route::any('/configuracao/historico/datas_historico/{robo}', 'ConfiguracaoController@datasHistorico')->name('datas_historico');
	Route::any('/configuracao/historico/carregar_versao/{versao}', 'ConfiguracaoController@carregarVersaoHistorico')->name('carregar_versao_historico');
	
	Route::get('/configuracao/retorno_robo/interface_configuracao/{robo}', 'ConfiguracaoController@getInterfaceConfiguracao');
	Route::get('/configuracao/retorno_robo/json_robo/{robo}', 'ConfiguracaoController@getJsonRobo');
	Route::get('/configuracao/retorno_robo/campos_robo/{robo}', 'ConfiguracaoController@getCamposRobo');
	Route::get('/configuracao/retorno_robo/valores_select/{campo}', 'ConfiguracaoController@getValoresSelect');
	Route::get('/configuracao/retorno_robo/usuario_padrao/{robo}', 'ConfiguracaoController@getUsuarioPadrao');
	Route::get('/configuracao/retorno_robo/campos_condicoes/{operadora?}', 'ConfiguracaoController@getCamposCondicoes');
	Route::get('/configuracao/retorno_robo/campos_dados_adicionais_interface', 'ConfiguracaoController@getCamposDadosAdicionaisInterface');
	Route::get('/configuracao/retorno_robo/acoes_interface/{tratativa}', 'ConfiguracaoController@getAcoesInterface');
	Route::get('/configuracao/retorno_robo/descricoes_acoes', 'ConfiguracaoController@getDescricoesAcoes');
	Route::get('/configuracao/retorno_robo/campos_comparativos_order', 'ConfiguracaoController@getCamposComparativosOrder');
	
	Route::post('/configuracao/retorno_robo/salvar_configuracao', 'ConfiguracaoController@salvarConfiguracao');
});

Route::middleware('auth')->namespace('Cron')->name('cron.')->group(function () {
	Route::any('/cron/lista/{resultado?}', 'CronController@Lista')->name('lista');
	Route::any('/cron/editar/{id?}', 'CronController@Editar')->name('editar');
	Route::get('/cron/ativar/{id?}', 'CronController@Ativar')->name('ativar');
});

#Default route
Route::any('/dashboard', function () {return view('dashboard');})->name('home')->middleware('auth');

Route::namespace('Hub')->group(function () {

	Route::any('/login', 'LoginController@entrar')->name('login');
	Route::any('/sair', 'LoginController@sair')->name('logout');
	Route::any('/modificar-senha/{usuario}', 'UsuarioController@mudar_senha')->name('hub.usuario.mudar.senha');

	Route::middleware('auth')->name('hub.')->group(function () {

		Route::any('/cadastro', 'LoginController@cadastro')->name('cadastro');
		Route::any('/permissionar/{key}', 'UsuarioController@permissionar')->name('usuario.permissionar');
		Route::any('/usuario/editar/{id?}', 'UsuarioController@editar')->name('usuario.editar');

		Route::middleware('permissao:hub.admin')->group(function () {

			Route::any('/config', 'ConfigController@geral')->name('config');

			Route::name('usuario.')->group(function () {

				Route::get('/usuario-gerar-senha/{usuario}', 'UsuarioController@gerar_senha')->name('gerar.senha');
				Route::any('/usuario', 'UsuarioController@lista')->name('lista');

			});

			Route::name('perfil.')->group(function () {

				Route::any('/Perfil', 'PerfilController@lista')->name('lista');

			});

		});

	});

});


/**
 * Contestador
 */

Route::namespace('Contestador')->prefix('/contestador')->middleware('permissao:contestador')->name('contestador.')->group(function () {

	Route::any('update-pedido-marcado', function () {
		Artisan::call('contestador:update_pedido_marcado');
		return 'Enviado!';
	});

	Route::Any('/pedido', 'PedidoController@listar')->name('pedido.listar');
	Route::Any('/pedido/ver/{id}', 'PedidoController@ver')->name('pedido.ver');
	
	Route::Any('/receita', 'ReceitaController@listar')->name('receita.listar');
	Route::Any('/receita/ver/{id}', 'ReceitaController@ver')->name('receita.ver');
	Route::Any('/receita/marcar-regra', 'ReceitaController@marcar_regra')->name('receita.marcar');

	Route::any('/competencia', 'CompetenciaController@listar')->name('competencia.listar');
	Route::any('/competencia/nova', 'CompetenciaController@novo')->name('competencia.novo');
	Route::any('/competencia/reprocessar/{id}', 'CompetenciaController@reprocessar')->middleware('permissao:contestador.admin')->name('competencia.reprocessar');
	
	Route::middleware('permissao:contestador.marcacao.operador|contestador.admin')->group(function () {
		
		Route::any('/arquivo', 'ArquivoController@listar')->name('arquivo.listar');
		Route::any('/arquivo/novo', 'ArquivoController@editar')->name('arquivo.novo');
		Route::any('/arquivo/editar/{id}', 'ArquivoController@editar')->name('arquivo.editar');
		Route::any('/arquivo/deletar/{id}', 'ArquivoController@deletar')->name('arquivo.deletar');
		Route::any('/arquivo/upload/{id}', 'ArquivoController@upload')->name('arquivo.upload');
		Route::any('/arquivo/download', 'ArquivoController@download')->name('arquivo.download');
		
		Route::any('/processo/listar', 'ProcessoController@listar')->name('processo.listar');
		Route::any('/processo/reprocessar/{id}', 'ProcessoController@reprocessar')->middleware('permissao:contestador.admin')->name('processo.reprocessar');
		Route::any('/processo/download/{id}', 'ProcessoController@download')->name('processo.download');

	});

	// Route::prefix('/marcador')->name('marcador.')->group(function () {

	// 	Route::any('/listar', 'MarcadorController@listar')->name('lista');
	// 	Route::any('/marcacoes', 'MarcadorController@marcacoes')->name('marcacoes');
	// 	Route::any('/marcar/{marcador}', 'MarcadorController@marcar')->name('marcar');
	// 	Route::any('/novo', 'MarcadorController@editar')->name('novo');
	// 	Route::any('/editar/{marcador}', 'MarcadorController@editar')->name('editar');
	// 	Route::any('/duplicar/{marcador}', 'MarcadorController@duplicar')->name('duplicar');

	// });

	Route::middleware('permissao:contestador.marcacao.editor')->group(function () {

		Route::any('regra/marcacao', 'RegraController@marcacao_listar')->name('regra.marcacao.listar');
		Route::any('regra/marcacao/nova', 'RegraController@marcacao_editar')->name('regra.marcacao.nova');
		Route::any('regra/marcacao/editar/{id}', 'RegraController@marcacao_editar')->name('regra.marcacao.editar');
		
		// Route::any('regra/apuracao_receita', 'RegraController@listar')->name('regra.listar.apuracaoreceita')->defaults('tipo','apuracao_receita');
		// Route::any('regra/comissao', 'RegraController@listar')->name('regra.listar.comissao')->defaults('tipo','comissao');
		
		// Route::any('/regra', 'RegraController@listar')->name('regra.listar');
		// Route::any('/regra/nova/{tipo?}', 'RegraController@nova')->name('regra.nova');
		// Route::any('/regra/editar/{id}', 'RegraController@editar')->name('regra.editar');
		
		// Route::any('/meta', 'MetaController@listar')->name('meta.listar');
		// Route::any('/remuneracao', 'TabelaController@remuneracao_listar')->name('remuneracao.listar');
		// Route::any('/remuneracao/nova', 'TabelaController@remuneracao_editar')->name('remuneracao.novo');
		// Route::any('/remuneracao/editar/{id}', 'TabelaController@remuneracao_editar')->name('remuneracao.editar');
		// Route::any('/remuneracao/deletar/{id}', 'TabelaController@remuneracao_deletar')->name('remuneracao.deletar');

	});

	Route::middleware('permissao:contestador.admin')->group(function () {

		Route::any('/config', 'ConfigController@geral')->name('config');

	});

});

/**
 * Catálogo
 */
 Route::namespace('Catalogo')->prefix('/catalogo')->name('catalogo.')->middleware('permissao:catalogo')->group(function () {

	Route::prefix('/contingencia')->name('contingencia.')->middleware('permissao:catalogo.contingencia')->group(function () {

		Route::any('/analisador-bundle', 'ContingenciaController@analizador_bundle')->name('analisador');

	});

});

/**
 * Alarmística
 */

/**
 * endpoint para o robo do Callel
*/
Route::get('dashboard-robo-acesso', 'Alarmistica\ApiController@listaLogs');


Route::namespace('Alarmistica')->prefix('/alarmistica')->middleware('permissao:alarmistica')->name('alarmistica.')->group(function () {

	Route::prefix('/api')->name('api.')->group(function () {

		Route::get('exibeIndicadoresMenu', 'ApiController@exibeIndicadoresMenu')->name('exibeIndicadoresMenu');
		Route::any('listaApis', 'ApiController@listaApis')->name('listaApis');

app/Models/Cron/Crons.php
<?php

namespace App\Models\Cron;

use Illuminate\Database\Eloquent\Model;

class Crons extends Model {

	#Configuração padrão do Eloquent para definição de qual tabela do banco de dados e qual conexão será usada para gerenciar esse model
	protected $table			= 'crons';
	protected $connection		= 'crons';
	public $timestamps = false;
	
}

app/Http/Controllers/Cron/CronController.php
<?php

namespace App\Http\Controllers\Cron;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CronController extends Controller {

    public function Lista(Request $request) {
        $resultado = null;

        if ($request->isMethod('post')) {
            $resultado = $this->atualizar();
        }

        $crons = \App\Models\Cron\Crons::orderBy('categoria')->orderBy('nome')->get();
        $lista = [];
        foreach ($crons as $cron) {
            $lista[$cron->categoria][] = $cron;
        }

        return view('cron/lista', [
                'resultado' => $resultado,
                'lista' => $lista,
                'format' => new \App\Helpers\Crons\Format()
            ]
        );
    }

    private function atualizar() {
        $dados = \App\Models\Cron\Crons::where('status', 1)->orderBy('categoria')->orderBy('nome')->get();
        $envio = [];

        foreach ($dados as $d) {
            $envio[$d['categoria']][] = $d;
        }

        $ch = curl_init(env('MAGENTO_API_HOST_INTERNO_CRON').'/api/v1/cron/redefinir');
        $header[] = 'Content-Type: application/json';
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($envio));
        curl_setopt($ch, CURLOPT_HTTPHEADER, $header);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_TIMEOUT, 5);

        $res = curl_exec($ch);
        $httpcode = curl_getinfo($ch, CURLINFO_HTTP_CODE);

        $msg = null;
        if ($httpcode != 200) {
            $msg = json_decode($res, true)['mensagem'];
            \Log::channel('cron')->error('Erro ao atualizar crons: '.$msg);
        }

        return ($httpcode == 200) ? 'Atualizado com sucesso' : 'Erro ao atualizar: '.$msg;
    }

    public function editar(Request $request, $id=null) {
        $salvo = null;
        $cron = \App\Models\Cron\Crons::find($id);
        if ($cron == null) {
            $cron = new \App\Models\Cron\Crons();
        }
        
        if ($request->isMethod('post')) {
            if ($request->submit == 'salvar') {
                $cron->nome = $request['nome'];
                $cron->hora = $this->getValorAgendamento($request['tipo_hora'], 'hora', $request);
                $cron->minuto = $this->getValorAgendamento($request['tipo_minuto'], 'minuto', $request);
                $cron->dia_semana =  @implode(",", $request['dia_semana']);
                $cron->dia_mes = @implode(",", $request['dia_mes']);
                $cron->mes = @implode(",", $request['mes']);
                $cron->timeout = $request['timeout'];
                $cron->comando = $request['comando'];
                $cron->parametro_adicional = $request['parametro_adicional'];
                $cron->descricao = $request['descricao'];
                $cron->categoria = (!empty($request['categoria'])) ? \mb_strtoupper($request['categoria']) : 'GERAL';
                $cron->status = $request['status'];
                $cron->save();
                $salvo = true;
            }

            if ($request->submit == 'excluir') {
                $cron->delete();

                return redirect()->route('cron.lista');
            }
        }
        
        return view('cron/editar', ['cron' => $cron, 'salvo' => $salvo]);
    }

    public function ativar(Request $request, $id=null) {
        $cron = \App\Models\Cron\Crons::find($id);
        $cron->status = !$cron->status;
        $cron->save();
        
        return ['OK' => true];
    }

    private function getValorAgendamento($tipo, $campo, $request) {
        if ($tipo == 'intervalo') {
            return "*/".$request[$campo.'_intervalo'];
        }

        if ($tipo == 'fixo') {
            return @implode(",", $request[$campo.'_fixo']);
        }
    }

}

resources/views/cron/editar.blade.php
@extends('layouts.admin')

@section('title', ($cron->id != null) ? 'Gerenciar Cron: '.$cron->nome :  'Novo cron')

@push('header.javascript')
<script>
    $(function() {
        $("#submit_excluir").click(function() {
            if (confirm('Excluir cron?')) {
                $(form).submit();
            }

            return false;
        });

        $(".radio_tipo").on('ifChanged', function(event){
            exibir($(this).val(), $(this).attr('name').replace("tipo_", ''));
        });

        exibir('{{(strstr($cron->hora, '/')) ? 'intervalo' : 'fixo'}}', 'hora');
        exibir('{{(strstr($cron->minuto, '/')) ? 'intervalo' : 'fixo'}}', 'minuto');
    });

    function exibir(exibir, campo) {
        var esconder = 'intervalo';
        if (exibir == 'intervalo') {
            esconder = 'fixo';
        }
        
        $(".select_"+campo+"_"+esconder).fadeOut('normal', function() {
            $(".select_"+campo+"_"+exibir).fadeIn();
        });

        $(':radio[name=tipo_'+campo+'][value='+exibir+']').iCheck('check');
    }
</script>
@endpush
@push('header.css')
    <link rel="stylesheet" href="{{url('css/cron/cron.css')}}">
@endpush
@section('content')

@if ($salvo)
<div class="row">
    <div class="col-md-12">
        <div class="callout callout-success">
            <p><b>Salvo com sucesso</b></p>
        </div>
    </div>
</div>
@endif

<button onclick="window.location='{{route('cron.lista')}}'" class="fa fa-arrow-left btn btn-primary" value='voltar'> Voltar para lista</button>    
<br>
<br>
<form class="row" method="post" action="{{route('cron.editar', ['id' => $cron->id])}}">
	<div class="col-md-12">
		@csrf
		<div class="box box-info">
            <div class="box-body">
                <div class="form-group">
                    <label for="nome" class="control-label">Nome</label>
                    <input type="text" class="form-control" name="nome" value="{{$cron->nome}}"/>
                </div>
                <div class='row'>
                    <div class='col-sm-3'>
                        <label class='control-label'>Hora</label>
                        <div class='well well-sm'>
                            <div class="btn-group" data-toggle="buttons">
                                <label class="btn btn-default">
                                    <input type="radio" name="tipo_hora" class='radio_tipo' value="intervalo" />Intervalo
                                </label> 
                                <label class="btn btn-default">
                                    <input type="radio" name="tipo_hora" class='radio_tipo' value="fixo" />Fixo
                                </label>
                            </div>
                            <span class='select_hora_intervalo' style='display: none'>
                                <div class="row row_intervalo">
                                    <div class="col-sm-3 cada">A cada</div>
                                    <div class="col-sm-3 text_intervalo">
                                        <input type="text" class="form-control input-sm intervalo" name="hora_intervalo" value="{{str_replace('*/', '', $cron->hora)}}"/>
                                    </div>
                                    <div class="col-sm-4 descricao_intervalo">Horas</div>
                                </div>
                            </span>
                            <span class='select_hora_fixo' style='display: none'><br>
                                <select class="form-control input-sm selectpicker" name="hora_fixo[]" data-action-box="1" data-none-selected-text="Nenhuma hora selecionada" multiple>
                                    <option value="*" {{(in_array('*', explode(',', $cron->hora))) ? 'selected' : ''}}>Todas</option>
                                    @for ($i=0;$i<=23;$i++)
                                        <option value="{{$i}}" {{(in_array((string) $i, explode(',', $cron->hora), true)) ? 'selected' : ''}}>{{$i}}:00</option>
                                    @endfor
                                </select>
                            </span>
                        </div>
                    </div>
                    <div class='col-sm-3'>
                        <label for="minuto" class="control-label">Minuto</label>
                        <div class="well well-sm">
                            <div class="btn-group" data-toggle="buttons">
                                <label class="btn btn-default">
                                    <input type="radio" name="tipo_minuto" class='radio_tipo' value="intervalo" />Intervalo
                                </label> 
                                <label class="btn btn-default">
                                    <input type="radio" name="tipo_minuto" class='radio_tipo' value="fixo" />Fixo
                                </label>
                            </div>
                            <span class='select_minuto_intervalo' style='display: none'>
                                <div class="row row_intervalo">
                                    <div class="col-sm-3 text-center cada">A cada</div>
                                    <div class="col-sm-3 text_intervalo">
                                        <input type="text" class="form-control input-sm intervalo" name="minuto_intervalo" value="{{str_replace('*/', '', $cron->minuto)}}"/>
                                    </div>
                                    <div class="col-sm-4 text-center descricao_intervalo">Minutos</div>
                                </div>
                            </span>
                            <span class='select_minuto_fixo' style='display: none'>
                                <select class="form-control input-sm selectpicker" name="minuto_fixo[]" data-action-box="1" data-none-selected-text="Nenhum minuto selecionado" multiple>
                                    <option value="*" {{(in_array('*', explode(',', $cron->minuto))) ? 'selected' : ''}}>Todos</option>
                                    @for ($i=0;$i<=59;$i++)
                                        <option value="{{$i}}" {{(in_array((string) $i, explode(',', $cron->minuto), true)) ? 'selected' : ''}}>{{$i}}</option>
                                    @endfor
                                </select>
                            </span>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class='col-sm-3'>
                        <label for="dia_mes" class="control-label">Dia da semana</label>
                        <div class="well well-sm">
                            <span class='select_dia_semana_intervalo'>
                                <div class="row row_intervalo">
                                    <div class="col-sm-12">
                                        <select class="form-control input-sm selectpicker" name="dia_semana[]" data-action-box="1" data-none-selected-text="Nenhum dia selecionado" multiple>
                                            <option value="*" {{(in_array('*', explode(',', $cron->dia_semana))) ? 'selected' : ''}}>Todos</option>
                                            <option value="0" {{(in_array('0', explode(',', $cron->dia_semana))) ? 'selected' : ''}}>Domingo</option>
                                            <option value="1" {{(in_array('1', explode(',', $cron->dia_semana))) ? 'selected' : ''}}>Segunda</option>
                                            <option value="2" {{(in_array('2', explode(',', $cron->dia_semana))) ? 'selected' : ''}}>Terça</option>
                                            <option value="3" {{(in_array('3', explode(',', $cron->dia_semana))) ? 'selected' : ''}}>Quarta</option>
                                            <option value="4" {{(in_array('4', explode(',', $cron->dia_semana))) ? 'selected' : ''}}>Quinta</option>
                                            <option value="5" {{(in_array('5', explode(',', $cron->dia_semana))) ? 'selected' : ''}}>Sexta</option>
                                            <option value="6" {{(in_array('6', explode(',', $cron->dia_semana))) ? 'selected' : ''}}>Sábado</option>
                                        </select>
                                    </div>
                                </div>
                            </span>
                        </div>
                    </div>
                    <div class='col-sm-3'>
                        <label for="dia_mes" class="control-label">Dia do mês</label>
                        <div class="well well-sm">
                            <span class='select_dia_mes_intervalo'>
                                <div class="row row_intervalo">
                                    <div class="col-sm-12">
                                        <select class="form-control input-sm selectpicker" name="dia_mes[]" data-action-box="1" data-none-selected-text="Nenhum dia selecionado" multiple>
                                        <option value="*" {{(in_array('*', explode(',', $cron->dia_mes))) ? 'selected' : ''}}>Todos</option>
                                        @for ($i=0;$i<=31;$i++)
                                            <option value="{{$i}}" {{(in_array((string) $i, explode(',', $cron->dia_mes), true)) ? 'selected' : ''}}>{{$i}}</option>
                                        @endfor
                                    </select>
                                    </div>
                                </div>
                            </span>
                        </div>
                    </div>
                    <div class='col-sm-3'>
                        <label for="dia_mes" class="control-label">Mês</label>
                        <div class="well well-sm">
                            <span class='select_mes_intervalo'>
                                <div class="row row_intervalo">
                                    <div class="col-sm-12">
                                    <select class="form-control input-sm selectpicker" name="mes[]" data-action-box="1" data-none-selected-text="Nenhum mês selecionado" multiple>
                                        <option value="*" {{(in_array('*', explode(',', $cron->mes))) ? 'selected' : ''}}>Todos</option>
                                        @for ($i=1;$i<=12;$i++)
                                            <option value="{{$i}}" {{(in_array((string) $i, explode(',', $cron->mes), true)) ? 'selected' : ''}}>{{$i}}</option>
                                        @endfor
                                    </select>
                                    </div>
                                </div>
                            </span>
                        </div>
                    </div>
                </div>  
                <div class="form-group">
                    <label for="comando" class="control-label">Comando (Caminho completo para o script)</label>
                    <input type="text" class="form-control" name="comando" value="{{$cron->comando}}"/>
                </div>
                <div class="form-group">
                    <label for="timeout" class="control-label">Timeout (Segundos)</label>
                    <input type="text" class="form-control" name="timeout" value="{{$cron->timeout}}"/>
                </div>
                <div class="form-group">
                    <label for="parametro_adicional" class="control-label">Parâmetro Adicional</label>
                    <input type="text" class="form-control" name="parametro_adicional" value="{{$cron->parametro_adicional}}"/>
                </div>
                <div class="form-group">
                    <label for="descricao" class="control-label">Descrição</label>
                    <input type="text" class="form-control" name="descricao" value="{{$cron->descricao}}"/>
                </div>
                <div class="form-group">
                    <label for="categoria" class="control-label">Categoria</label>
                    <input type="text" class="form-control" name="categoria" value="{{$cron->categoria}}"/>
                </div>
                <div class="form-group">
                    <label for="status" class="control-label">Status</label>
                    <select class="form-control" name="status">
                        <option value="1" {{($cron->status == 0) ? 'selected' : ''}}>Ativo</option>
                        <option value="0" {{($cron->status == 0) ? 'selected' : ''}}>Inativo</option>
                    </select>
                </div>
            </div>
            <div class="box-footer">
                <div class="row">
                    <div class="col-md-2">
                        <button type="submit" class="btn btn-success" name='submit' value='salvar'>Salvar</button>
                        @if ($cron->id != null)
                        <button type="submit" class="btn btn-danger" name='submit' id='submit_excluir' value='excluir'>Excluir</button>
                        @endif
                    </div>
                </div>
            </div>
		</div>
	</div>
	
</form>

@endsection