routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

#API ORDER
// Route::get('api_order/json_elegibilidade/{order}/{segmento?}', function ($order, $segmento = 'POS_PAGO') {

// 	return App\Helpers\Tim\ApiOrdem::GetDataElegibilidade(\App\Models\Magento\Consumer\Order::with(['adicionais','origem','addresses','customer','webjump'])->findOrFail($order), $segmento);

// });

// Route::get('api_order/json_envio/{order}', function ($order) {

// 	return App\Helpers\Tim\ApiOrdem::GetDataEnvio(\App\Models\Magento\Consumer\Order::with(['adicionais','origem','addresses','customer','webjump'])->findOrFail($order));

// });

#Test Route
Route::any('test', 'TestController');
Route::any('info', function () {
	phpinfo();
});

Route::namespace('Portal')->name('portal.')->group(function() {
	Route::any('/portal/login', 'PortalController@login')->name('login_portal');
	Route::any('/portal/senha', 'PortalController@alterarSenha')->name('alterar_senha_portal');
	Route::middleware('portal')->group(function() {
		Route::get('/portal', 'PortalController@grid')->name('grid_portal');
		Route::any('/portal/logout', 'PortalController@logout')->name('logout_portal');
		Route::get('/portal/dados_pedido/{pedido?}', 'PortalController@dadosPedido')->name('dados_pedido_portal');
	});
});

Route::middleware('auth')->namespace('Configuracao')->name('configuracao.')->group(function () {
	Route::get('/configuracao/lista_tratativas', 'ConfiguracaoController@listaTratativas')->name('lista_tratativas');
	Route::any('/configuracao/editar_tratativa/{id?}', 'ConfiguracaoController@editarTratativa')->name('editar_tratativa');
	Route::get('/configuracao/lista_acoes', 'ConfiguracaoController@listaAcoes')->name('lista_acoes');
	Route::any('/configuracao/editar_acao/{id?}', 'ConfiguracaoController@editarAcao')->name('editar_acao');
	Route::get('/configuracao/lista_condicoes_especiais', 'ConfiguracaoController@listaCondicoesEspeciais')->name('lista_condicoes_especiais');
	Route::any('/configuracao/editar_condicao_especial/{id?}', 'ConfiguracaoController@editarCondicaoEspecial')->name('editar_condicao_especial');
	Route::get('/configuracao/lista_campos', 'ConfiguracaoController@listaCampos')->name('lista_campos');
	Route::any('/configuracao/editar_campo/{id?}', 'ConfiguracaoController@editarCampo')->name('editar_campo');

	Route::any('/configuracao', 'ConfiguracaoController@exibir')->name('tratativas_automaticas');
	Route::any('/configuracao/historico', 'ConfiguracaoController@exibirHistorico')->name('historico');
	Route::any('/configuracao/historico/datas_historico/{robo}', 'ConfiguracaoController@datasHistorico')->name('datas_historico');
	Route::any('/configuracao/historico/carregar_versao/{versao}', 'ConfiguracaoController@carregarVersaoHistorico')->name('carregar_versao_historico');
	
	Route::get('/configuracao/retorno_robo/interface_configuracao/{robo}', 'ConfiguracaoController@getInterfaceConfiguracao');
	Route::get('/configuracao/retorno_robo/json_robo/{robo}', 'ConfiguracaoController@getJsonRobo');
	Route::get('/configuracao/retorno_robo/campos_robo/{robo}', 'ConfiguracaoController@getCamposRobo');
	Route::get('/configuracao/retorno_robo/valores_select/{campo}', 'ConfiguracaoController@getValoresSelect');
	Route::get('/configuracao/retorno_robo/usuario_padrao/{robo}', 'ConfiguracaoController@getUsuarioPadrao');
	Route::get('/configuracao/retorno_robo/campos_condicoes/{operadora?}', 'ConfiguracaoController@getCamposCondicoes');
	Route::get('/configuracao/retorno_robo/campos_dados_adicionais_interface', 'ConfiguracaoController@getCamposDadosAdicionaisInterface');
	Route::get('/configuracao/retorno_robo/acoes_interface/{tratativa}', 'ConfiguracaoController@getAcoesInterface');
	Route::get('/configuracao/retorno_robo/descricoes_acoes', 'ConfiguracaoController@getDescricoesAcoes');
	Route::get('/configuracao/retorno_robo/campos_comparativos_order', 'ConfiguracaoController@getCamposComparativosOrder');
	
	Route::post('/configuracao/retorno_robo/salvar_configuracao', 'ConfiguracaoController@salvarConfiguracao');
});

Route::middleware('auth')->namespace('Cron')->name('cron.')->group(function () {
	Route::any('/cron/lista/{resultado?}', 'CronController@Lista')->name('lista');
	Route::any('/cron/editar/{id?}', 'CronController@Editar')->name('editar');
	Route::get('/cron/ativar/{id?}', 'CronController@Ativar')->name('ativar');
});

#Default route
Route::any('/dashboard', function () {return view('dashboard');})->name('home')->middleware('auth');

Route::namespace('Hub')->group(function () {

	Route::any('/login', 'LoginController@entrar')->name('login');
	Route::any('/sair', 'LoginController@sair')->name('logout');
	Route::any('/modificar-senha/{usuario}', 'UsuarioController@mudar_senha')->name('hub.usuario.mudar.senha');

	Route::middleware('auth')->name('hub.')->group(function () {

		Route::any('/cadastro', 'LoginController@cadastro')->name('cadastro');
		Route::any('/permissionar/{key}', 'UsuarioController@permissionar')->name('usuario.permissionar');
		Route::any('/usuario/editar/{id?}', 'UsuarioController@editar')->name('usuario.editar');

		Route::middleware('permissao:hub.admin')->group(function () {

			Route::any('/config', 'ConfigController@geral')->name('config');

			Route::name('usuario.')->group(function () {

				Route::get('/usuario-gerar-senha/{usuario}', 'UsuarioController@gerar_senha')->name('gerar.senha');
				Route::any('/usuario', 'UsuarioController@lista')->name('lista');

			});

			Route::name('perfil.')->group(function () {

				Route::any('/Perfil', 'PerfilController@lista')->name('lista');

			});

		});

	});

});


/**
 * Contestador
 */

Route::namespace('Contestador')->prefix('/contestador')->middleware('permissao:contestador')->name('contestador.')->group(function () {

	Route::any('update-pedido-marcado', function () {
		Artisan::call('contestador:update_pedido_marcado');
		return 'Enviado!';
	});

	Route::Any('/pedido', 'PedidoController@listar')->name('pedido.listar');
	Route::Any('/pedido/ver/{id}', 'PedidoController@ver')->name('pedido.ver');
	
	Route::Any('/receita', 'ReceitaController@listar')->name('receita.listar');
	Route::Any('/receita/ver/{id}', 'ReceitaController@ver')->name('receita.ver');
	Route::Any('/receita/marcar-regra', 'ReceitaController@marcar_regra')->name('receita.marcar');

	Route::any('/competencia', 'CompetenciaController@listar')->name('competencia.listar');
	Route::any('/competencia/nova', 'CompetenciaController@novo')->name('competencia.novo');
	Route::any('/competencia/reprocessar/{id}', 'CompetenciaController@reprocessar')->middleware('permissao:contestador.admin')->name('competencia.reprocessar');
	
	Route::middleware('permissao:contestador.marcacao.operador|contestador.admin')->group(function () {
		
		Route::any('/arquivo', 'ArquivoController@listar')->name('arquivo.listar');
		Route::any('/arquivo/novo', 'ArquivoController@editar')->name('arquivo.novo');
		Route::any('/arquivo/editar/{id}', 'ArquivoController@editar')->name('arquivo.editar');
		Route::any('/arquivo/deletar/{id}', 'ArquivoController@deletar')->name('arquivo.deletar');
		Route::any('/arquivo/upload/{id}', 'ArquivoController@upload')->name('arquivo.upload');
		Route::any('/arquivo/download', 'ArquivoController@download')->name('arquivo.download');
		
		Route::any('/processo/listar', 'ProcessoController@listar')->name('processo.listar');
		Route::any('/processo/reprocessar/{id}', 'ProcessoController@reprocessar')->middleware('permissao:contestador.admin')->name('processo.reprocessar');
		Route::any('/processo/download/{id}', 'ProcessoController@download')->name('processo.download');

	});

	// Route::prefix('/marcador')->name('marcador.')->group(function () {

	// 	Route::any('/listar', 'MarcadorController@listar')->name('lista');
	// 	Route::any('/marcacoes', 'MarcadorController@marcacoes')->name('marcacoes');
	// 	Route::any('/marcar/{marcador}', 'MarcadorController@marcar')->name('marcar');
	// 	Route::any('/novo', 'MarcadorController@editar')->name('novo');
	// 	Route::any('/editar/{marcador}', 'MarcadorController@editar')->name('editar');
	// 	Route::any('/duplicar/{marcador}', 'MarcadorController@duplicar')->name('duplicar');

	// });

	Route::middleware('permissao:contestador.marcacao.editor')->group(function () {

		Route::any('regra/marcacao', 'RegraController@marcacao_listar')->name('regra.marcacao.listar');
		Route::any('regra/marcacao/nova', 'RegraController@marcacao_editar')->name('regra.marcacao.nova');
		Route::any('regra/marcacao/editar/{id}', 'RegraController@marcacao_editar')->name('regra.marcacao.editar');
		
		// Route::any('regra/apuracao_receita', 'RegraController@listar')->name('regra.listar.apuracaoreceita')->defaults('tipo','apuracao_receita');
		// Route::any('regra/comissao', 'RegraController@listar')->name('regra.listar.comissao')->defaults('tipo','comissao');
		
		// Route::any('/regra', 'RegraController@listar')->name('regra.listar');
		// Route::any('/regra/nova/{tipo?}', 'RegraController@nova')->name('regra.nova');
		// Route::any('/regra/editar/{id}', 'RegraController@editar')->name('regra.editar');
		
		// Route::any('/meta', 'MetaController@listar')->name('meta.listar');
		// Route::any('/remuneracao', 'TabelaController@remuneracao_listar')->name('remuneracao.listar');
		// Route::any('/remuneracao/nova', 'TabelaController@remuneracao_editar')->name('remuneracao.novo');
		// Route::any('/remuneracao/editar/{id}', 'TabelaController@remuneracao_editar')->name('remuneracao.editar');
		// Route::any('/remuneracao/deletar/{id}', 'TabelaController@remuneracao_deletar')->name('remuneracao.deletar');

	});

app/Models/Configuracao/Acoes.php
<?php

namespace App\Models\Configuracao;

use Illuminate\Database\Eloquent\Model;

class Acoes extends Model {

	#Configuração padrão do Eloquent para definição de qual tabela do banco de dados e qual conexão será usada para gerenciar esse model
	protected $table			= 'acoes';
	protected $connection		= 'configuracao';
	public $timestamps = false;
	
}

app/Models/Configuracao/AcoesTratativas.php
<?php

namespace App\Models\Configuracao;

use Illuminate\Database\Eloquent\Model;

class AcoesTratativas extends Model {

	#Configuração padrão do Eloquent para definição de qual tabela do banco de dados e qual conexão será usada para gerenciar esse model
	protected $table			= 'acoes_tratativas';
	protected $connection		= 'configuracao';
	public $timestamps = false;
	
}

app/Models/Configuracao/CondicoesEspeciais.php
<?php

namespace App\Models\Configuracao;

use Illuminate\Database\Eloquent\Model;

class CondicoesEspeciais extends Model {

	#Configuração padrão do Eloquent para definição de qual tabela do banco de dados e qual conexão será usada para gerenciar esse model
	protected $table			= 'condicoes_especiais';
	protected $connection		= 'configuracao';
	public $timestamps = false;
	
}

app/Models/Configuracao/Configuracao.php
<?php

namespace App\Models\Configuracao;

use Jenssegers\Mongodb\Eloquent\Model;

class Configuracao extends Model {

	#Configuração padrão do Eloquent para definição de qual tabela do banco de dados e qual conexão será usada para gerenciar esse model
	protected $table			= 'configuracao';
	protected $connection		= 'alarmistica_mongo';
	
}

app/Models/Configuracao/ConfiguracaoHistorico.php
<?php

namespace App\Models\Configuracao;

use Jenssegers\Mongodb\Eloquent\Model;

class ConfiguracaoHistorico extends Model {

    const UPDATED_AT = null; 

	#Configuração padrão do Eloquent para definição de qual tabela do banco de dados e qual conexão será usada para gerenciar esse model
	protected $table			= 'configuracao_historico';
	protected $connection		= 'alarmistica_mongo';
	
}

app/Models/Configuracao/Labels.php
<?php

namespace App\Models\Configuracao;

use Illuminate\Database\Eloquent\Model;

class Labels extends Model {

	#Configuração padrão do Eloquent para definição de qual tabela do banco de dados e qual conexão será usada para gerenciar esse model
	protected $table			= 'labels';
	protected $connection		= 'configuracao';
	public $timestamps = false;
	
}

app/Models/Configuracao/Tratativas.php
<?php

namespace App\Models\Configuracao;

use Illuminate\Database\Eloquent\Model;

class Tratativas extends Model {

	#Configuração padrão do Eloquent para definição de qual tabela do banco de dados e qual conexão será usada para gerenciar esse model
	protected $table			= 'tratativas';
	protected $connection		= 'configuracao';
	public $timestamps = false;
	
}

resources/views/configuracao/editar_acao.blade.php
@extends('layouts.admin')

@section('title', 'Gerenciar Ação: '.$acao->label)

@push('header.javascript')
<script>
    $(function() {
        $("#submit_excluir").click(function() {
            if (confirm('Excluir ação?')) {
                $(form).submit();
            }

            return false;
        })
    });
</script>
@endpush

@section('content')

@if ($salvo)
<div class="row">
    <div class="col-md-12">
        <div class="callout callout-success">
            <p><b>Salvo com sucesso</b></p>
        </div>
    </div>
</div>
@endif

<form class="row" method="post" action="{{route('configuracao.editar_acao', ['id' => $acao->id])}}">
	<div class="col-md-12">
		@csrf
		<div class="box box-info">
            <div class="box-body">
                <div class="form-group">
                    <label for="rotulo" class="col-sm-12 control-label">Rótulo</label>
                    <input type="text" class="form-control" name="rotulo" value="{{$acao->label}}"/>
                </div>
                <div class="form-group">
                    <label for="valor" class="col-sm-12 control-label">Valor (Método acionado)</label>
                    <input type="text" class="form-control" name="valor" value="{{$acao->valor}}"/>
                </div>
                <div class="form-group">
                    <label for="descricao" class="col-sm-12 control-label">Descrição (Separar cada item com vírgula)</label>
                    <input type="text" class="form-control" name="descricao" value="{{$acao->descricao}}"/>
                </div>
                <div class="form-group">
                    <label for="dados_adicionais" class="col-sm-12 control-label">Dados Adicionais (Separar cada item com vírgula)</label>
                    <input type="text" class="form-control" name="dados_adicionais" value="{{$acao->dados_adicionais}}"/>
                </div>
            </div>
            <div class="box-footer">
                <div class="row">
                    <div class="col-md-2">
                        <button type="submit" class="btn btn-success" name='submit' value='salvar'>Salvar</button>    
                        <button type="submit" class="btn btn-danger" name='submit' id='submit_excluir' value='excluir'>Excluir</button>
                    </div>
                </div>
            </div>
		</div>
	</div>
	
</form>

@endsection

resources/views/configuracao/editar_campo.blade.php
@extends('layouts.admin')

@section('title', 'Gerenciar Campo: '.$campo->label)

@push('header.javascript')
<script>
    $(function() {
        $("#submit_excluir").click(function() {
            if (confirm('Excluir campo?')) {
                $(form).submit();
            }

            return false;
        })
    });
</script>
@endpush

@section('content')
@push('header.css')
<style type="text/css">
    input[type=checkbox], .iCheck-helper {
        height: 20px !important;
        position: relative !important;
        opacity: 1 !important;
        width: 14px !important;
        left: 1px !important;
        float: left;
    }
    .iCheck-helper {
        left: -20px !important;
        opacity: 0 !important;
    }
</style>
@endpush

@if ($salvo)
<div class="row">
    <div class="col-md-12">
        <div class="callout callout-success">
            <p><b>Salvo com sucesso</b></p>
        </div>
    </div>
</div>
@endif

<form class="row" method="post" action="{{route('configuracao.editar_campo', ['id' => $campo->id])}}">
	<div class="col-md-12">
		@csrf
		<div class="box box-info">
            <div class="box-body">
                <div class="form-group">
                    <label for="rotulo" class="col-sm-12 control-label">Rótulo</label>
                    <input type="text" class="form-control" name="rotulo" value="{{$campo->label}}"/>
                </div>
                <div class="form-group">
                    <label for="valor" class="col-sm-12 control-label">Valor (usado na execução da tratativa)</label>
                    <input type="text" class="form-control" name="valor" value="{{$campo->valor}}"/>
                </div>
                <div class="form-group">
                    <input type="checkbox" name="exibir_como_condicao" id="exibir_como_condicao" value="1" {{($campo->exibir_como_condicao) ? 'checked': ''}}/>
                    <span style='line-height:18px;margin-left: -10px;margin-right: 15px;'><label class="control-label">Exibir Como Condição</label></span>
                </div>
                <div class="form-group">
                    <input type="checkbox" name="exibir_como_dado_adicional" id="exibir_como_dado_adicional" value="1" {{($campo->exibir_como_dado_adicional) ? 'checked': ''}}/>
                    <span style='line-height:18px;margin-left: -10px;margin-right: 15px;'><label class="control-label">Exibir Como Dado Adicional</label></span>
                </div>
                <div class="form-group">
                    <input type="checkbox" name="exibir_como_comparativo" id="exibir_como_comparativo" value="1" {{($campo->exibir_como_comparativo) ? 'checked': ''}}/>
                    <span style='line-height:18px;margin-left: -10px;margin-right: 15px;'><label class="control-label">Exibir Como Comparativo</label></span>
                </div>
            </div>
            <div class="box-footer">
                <div class="row">
                    <div class="col-md-2">
                        <button type="submit" class="btn btn-success" name='submit' value='salvar'>Salvar</button>    
                        <button type="submit" class="btn btn-danger" name='submit' id='submit_excluir' value='excluir'>Excluir</button>
                    </div>
                </div>
            </div>
		</div>
	</div>
	
</form>

@endsection

resources/views/configuracao/editar_condicao_especial.blade.php
@extends('layouts.admin')

@section('title', 'Gerenciar Condição Especial: '.$condicao_especial->label)

@push('header.javascript')
<script>
    $(function() {
        $("#submit_excluir").click(function() {
            if (confirm('Excluir condição especial?')) {
                $(form).submit();
            }

            return false;
        })
    });
</script>
@endpush

@section('content')

@if ($salvo)
<div class="row">
    <div class="col-md-12">
        <div class="callout callout-success">
            <p><b>Salvo com sucesso</b></p>
        </div>
    </div>
</div>
@endif

<form class="row" method="post" action="{{route('configuracao.editar_condicao_especial', ['id' => $condicao_especial->id])}}">
	<div class="col-md-12">
		@csrf
		<div class="box box-info">
            <div class="box-body">
                <div class="form-group">
                    <label for="rotulo" class="col-sm-12 control-label">Rótulo</label>
                    <input type="text" class="form-control" name="rotulo" value="{{$condicao_especial->label}}"/>
                </div>
                <div class="form-group">
                    <label for="valor" class="col-sm-12 control-label">Valor (Método acionado)</label>
                    <input type="text" class="form-control" name="valor" value="{{$condicao_especial->valor}}"/>
                </div>
                <div class="form-group">
                    <label for="operadora" class="col-sm-12 control-label">Operadora</label>
                    <select class="form-control" name="operadora">
                        <option value="" {{('' == $condicao_especial->operadora) ? 'selected' : ''}}>Todas</option>
                        @foreach ($operadoras as $operadora)
                            <option value="{{$operadora->value}}" {{(mb_strtolower($operadora->value) == mb_strtolower($condicao_especial->operadora)) ? 'selected' : ''}}>{{$operadora->text}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="box-footer">
                <div class="row">
                    <div class="col-md-2">
                        <button type="submit" class="btn btn-success" name='submit' value='salvar'>Salvar</button>    
                        <button type="submit" class="btn btn-danger" name='submit' id='submit_excluir' value='excluir'>Excluir</button>
                    </div>
                </div>
            </div>
		</div>
	</div>
	
</form>

@endsection

resources/views/configuracao/editar_tratativa.blade.php
@extends('layouts.admin')

@section('title', 'Gerenciar Tratativa: '.$tratativa->label)

@push('header.javascript')
<script>
    $(function() {
        $("#submit_excluir").click(function() {
            if (confirm('Excluir tratativa?')) {
                $(form).submit();
            }

            return false;
        })
    });
</script>
@endpush

@section('content')

@if ($salvo)
<div class="row">
    <div class="col-md-12">
        <div class="callout callout-success">
            <p><b>Salvo com sucesso</b></p>
        </div>
    </div>
</div>
@endif

<form class="row" method="post" action="{{route('configuracao.editar_tratativa', ['id' => $tratativa->id])}}">
	<div class="col-md-12">
		@csrf
		<div class="box box-info">
            <div class="box-body">
                <div class="form-group">
                    <label for="rotulo" class="col-sm-12 control-label">Rótulo</label>
                    <input type="text" class="form-control" name="rotulo" value="{{$tratativa->label}}"/>
                </div>
                <div class="form-group">
                    <label for="nome" class="col-sm-12 control-label">Nome (operadora.nome_processo)</label>
                    <input type="text" class="form-control" name="nome" value="{{$tratativa->nome}}"/>
                </div>
                <div class="form-group">
                    <label for="status" class="col-sm-12 control-label">Ações</label>
                    <select class="form-control selectpicker" name="acoes[]" data-action-box="1" data-deselect-all-text="Remover seleção" data-select-all-text="Selecionar todos" data-none-selected-text="Nenhuma ação associada" multiple>
                        @foreach ($acoes as $acao)
                            <option value="{{$acao->id}}" {{(is_array($acoes_tratativa) && in_array($acao->id, $acoes_tratativa)) ? 'selected' : ''}}>{{$acao->label}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="box-footer">
                <div class="row">
                    <div class="col-md-2">
                        <button type="submit" class="btn btn-success" name='submit' value='salvar'>Salvar</button>    
                        <button type="submit" class="btn btn-danger" name='submit' id='submit_excluir' value='excluir'>Excluir</button>
                    </div>
                </div>
            </div>
		</div>
	</div>	
</form>

@endsection