routes/web.php
	Route::any('/gravar_pedido_fila/{fila}/{pedido}', 'FilasMagentoController@GravarPedidoFila')->name('gravar_pedido_fila');
});

/**
 * Pós-venda
 */
Route::namespace('Posvenda')->prefix('/posvenda')->middleware('permissao:posvenda')->name('posvenda.')->group(function () {
	Route::get('/registrar_atendimentos','PosVendaController@registrarAtendimentos')->name('registrar_atendimentos');
	Route::any('/listar_atendimentos','PosVendaController@listarAtendimentos')->name('listar_atendimentos');
	Route::post('/atendimentos.salvar','PosVendaController@salvarAtendimento')->name('salvar_atendimento');
	Route::post('/aviso.salvar','PosVendaController@salvarAviso')->name('salvar_aviso');
	Route::get('/buscar_motivos/{id?}','PosVendaController@buscarMotivos')->name('buscar-motivos');
	Route::get('/buscar_atendimento_por_motivo', 'PosVendaController@buscarAtendimentoPorPedido')->name('buscar-por-pedido');
	Route::get('/search_mortivos/{id?}','PosVendaController@seachMotivos')->name('search-motivos');
	Route::get('/busca_comentarios/{id?}','PosVendaController@buscarComentarios')->name('buscar-comentarios');
	Route::get('/busca_origens','PosVendaController@buscarOrigens')->name('buscar-origens');
	
	Route::middleware('permissao:posvenda.admin')->group(function () {
		Route::get('/deletar-atendimento/{id?}','PosVendaController@deletarAtendimento')->name("posvenda.deletar");
		Route::get('/adicionar_opcoes','PosVendaController@adicionarOpcoes')->name('adicionar_opcoes');
		Route::get('/alterar_opcoes','PosVendaController@alterarOpcoes')->name('alterar_opcoes');
		Route::get('/status','PosVendaController@buscarStatus');
		Route::any('/administrar_relacoes_motivos/{id?}','PosVendaController@administrarRelacoesMotivos')->name('administrar_relacoes_motivos');
		Route::get('/listar_motivos','PosVendaController@listarMotivos')->name('listar_motivos');
		Route::post('/atendimentos.salvar_opcoes','PosVendaController@salvarOpcoes')->name('salvar_opcoes');
		Route::post('/atendimentos.salvar_alterar_opcoes','PosVendaController@salvarAlterarOpcoes')->name('salvar_alterar_opcoes');
		Route::post('/cadastrar','PosVendaController@cadastrarAtendimento')->name('posvenda.cadastrar');
	});
});

/**
 * Magento
 */

Route::prefix('/magento')->namespace('Magento')->name('magento.')->group(function () {

	Route::any('vincular-login-magento', 'LoginController@vincular')->name('vincular');

	Route::any('alterar-dia-vencimento', 'PedidoController@dia_vencimento')->name('dia_vencimento');
	Route::any('atualizar-nomenclatura-sap', 'PedidoController@atualizar_nomenclatura')->name('nomenclaturasap');

	Route::any('/pedidos', 'PedidoController@listar')->name('pedido.listar');
	Route::any('/pedidos/ver/{pedido}', 'PedidoController@ver')->name('pedido.ver');

	Route::any('status-motivos-listar', 'MotivoController@listar')->name('motivos.listar');
	Route::any('status-motivos-criar', 'MotivoController@criar')->name('motivos.criar');
	Route::any('admin-user-base-listar', 'AdminUserBaseController@listar')->name('adminuser.listar');
	Route::any('admin-user-base-criar', 'AdminUserBaseController@criar')->name('adminuser.criar');
	
	Route::any('json-api-tim/{engine}/{versao}/{json}/{pedido}/{simulation?}', 'PedidoController@get_json_api_tim')
		->where([
			'engine' => 'cubo|tim',
			'versao' => 'v(3|5)',
			'json' => 'elegibilidade|order',
			'simulation' => 'avera']
		)
		->name('pedido.jsonapi')
	;

});

/**
 * Importador
 */

Route::namespace('Importador')->prefix('/importador')->middleware('permissao:importador')->name('importador.')->group(function () {

	Route::any('/importar/{id?}', 'ImportadorController@importar')->name('importar');

	Route::middleware('permissao:importador.downgrade')->group(function () {
		Route::get('/downgrade-tim-importar','ImportadorController@downgradeTimImportar')->name('downgradetim');
		Route::post('/downgrade-tim-importar','ImportadorController@downgradeTimImportar')->name('downgradetim_send');
		Route::get('/downgrade-vivo-importar','ImportadorController@downgradeVivoImportar')->name('downgradeVivo');
		Route::post('/downgrade-vivo-importar','ImportadorController@downgradeVivoImportar')->name('downgradevivo_send');
		Route::get('/downgrade-listar','ImportadorController@listar')->name('downgrade-listar');
	});
	
	Route::middleware('permissao:importador')->group(function () {
		Route::any('/status-pedido-importar','ImportadorController@statusPedidoImportar')->name('statuspedido');
		Route::get('/download-modelo-planilha', 'ImportadorController@downloadModeloPlanilha')->name('downloadplanilha');
		Route::any('/varejo-loja','ImportadorController@importarVarejoLoja')->name('varejoloja');
		Route::any('/cpf-vendedor','ImportadorController@cpf_vendedor')->name('cpfvendedor');
		Route::any('/phone-number','ImportadorController@phone_number')->name('phonenumber');
		Route::any('/decriptador-pedidos','ImportadorController@decrypt')->name('decrypt');
	});
});

/**
 * retornos
 */
Route::namespace('Retornos')->prefix('/retornos')->middleware('permissao:robo.retornos')->name('retornos.')->group(function () {
	Route::prefix('/tim')->namespace('Tim')->name('tim.')->group(function () {
		Route::get('/consulta-ordem','HistoricoController@consultaOrdem')->name('historicos.consultaordem');
	});
});

Route::namespace("Lojaonline")->prefix('/lojaonline')->name('lojaonline.')->group(function () {

	Route::any('enviar-pedidos-email', function () {
		Artisan::call('lojaonline:relatorio_crivo');
		return 'Enviado!';
	});

	Route::any('/api/claro/{data_inicio}/{data_fim}', 'ApiController@pedidos_claro')->name('pedidos.claro');
	Route::any('/api/claro_prospect/{data_inicio}/{data_fim}', 'ApiController@pedidos_claro_prospect')->name('pedidos.claro_prospect');
	Route::any('/api/claro_pre/{data_inicio}/{data_fim}', 'ApiController@pedidos_claro_pre')->name('pedidos.claro_pre');
	Route::any('/api/claro_pos/{data_inicio}/{data_fim}', 'ApiController@pedidos_claro_pos')->name('pedidos.claro_pos');

	Route::any('/pedidos/{loja}', 'PedidosController@listar')->name('pedidos.listar');

});

/**
 * Colmeia
 */

###############################
#suporte rotas antigas
###############################

#Route::any('/lista-colmeia','Colmeia\ArmarioController@lista');
Route::get('/busca-chip-estoque/{serial}', 'Colmeia\Api\v1\ProdutoController@check_serial_exists');
Route::get('/api-picking-automatico/{serial?}/{sku?}', 'Colmeia\Api\v1\ProdutoController@check_picking');
Route::get('/liberar-chip-colmeia/{nota}/{pedido}/{serial}/{sku}/{imei?}', 'Colmeia\Api\v1\ProdutoController@liberar_chip');
Route::get('/liberar-aparelho-colmeia/{nota}/{pedido}/{imei}', 'Colmeia\Api\v1\ProdutoController@liberar_aparelho');
Route::get('/retorna-sku/{serial}','ProdutoController@busca_sku');

Route::any('/retorna-chip-disponivel//{pedido?}', 'Colmeia\Api\v1\PosicaoController@desalocar_pedido');
Route::any('/retorna-chip-disponivel/{serial?}/{pedido?}', 'Colmeia\Api\v1\PosicaoController@desalocar');
Route::get('/chamada-chip-colmeia-pedido/{pedido}/{sku}/{serialSaida?}', 'Colmeia\Api\v1\PosicaoController@reservar');

###############################
#novas rotas
###############################
Route::namespace('Colmeia')->prefix('/colmeia')->name('colmeia.')->group(function () {

	Route::prefix('/api')->namespace('Api')->name('api.')->group(function () {

		// #Versão 1
		// Route::namespace('/v1')->prefix('v1')->group(function () {

		// 	Route::get('/seleciona-chip/{pedido}/{sku}/{serialSaida?}', 'PosicaoController@reservar');

		// });

		Route::prefix('v2')->namespace('v2')->name('v2.')->group(function () {

			Route::any('check-serial/{serial?}', 'ProdutoController@check_serial')->name('checkserial');
			Route::any('pode-alocar/{serial}', 'ProdutoController@pode_alocar')->name('podealocar');
			
			Route::any('produto-detalhe', 'ProdutoController@detalhe')->name('produto.detalhe');
			#Route::post('produto-detalhe', 'ProdutoController@detalhe')->name('produto.detalhe');
			
			
		});

		Route::prefix('v3')->namespace('v3')->name('v3.')->group(function () {

			Route::post('get-jundsoft-data', 'JundController@get_data')->name('jundsoft.getdata');
			Route::post('get-jundsoft-data-batch', 'JundController@get_data_batch')->name('jundsoft.getdata');

		});
	
	});

	Route::middleware('permissao:colmeia|colmeia.serial')->group(function () {

		Route::any('/config', 'ConfigController@geral')->name('config');
		Route::any('gerador-regex-sku', 'SkuController@gerador_regex')->name('sku.regex');

		Route::prefix('/magento')->name('magento.')->group(function () {

			Route::any('/atualizar-pedidos', 'MagentoController@atualizar_pedidos')->name('pedido.atualizar');
		
		});

		Route::prefix('/migracao')->name('migracao.')->group(function () {

			Route::any('/', 'MigracaoController');
			Route::any('/operadoras', 'MigracaoController@operadoras');

		});

		#armário
		Route::prefix('/armario')->name('armario.')->group(function () {

			Route::any('lista', 'ArmarioController@lista')->name('lista');
			Route::any('adicionar', 'ArmarioController@editar')->name('adicionar');
			Route::any('editar/{id?}', 'ArmarioController@editar')->name('editar');
			Route::any('desalocar/{id?}', 'ArmarioController@desalocar')->name('desalocar');

		});

		Route::any('/jundsoft', 'JundsoftController@listar')->name('jundsoft.listar');
		Route::any('/jundsoft/novo', 'JundsoftController@editar')->name('jundsoft.novo');
		Route::any('/jundsoft/editar/{id}', 'JundsoftController@editar')->name('jundsoft.editar');
		Route::any('/jundsoft/deletar/{id}', 'JundsoftController@deletar')->name('jundsoft.deletar');

		#Nota Fiscal
		Route::prefix('/nfe')->name('nfe.')->group(function () {

			Route::any('importar', 'NfeController@importar')->name('importar');
			Route::any('listar/{id}', 'NfeController@listar_detalhe_id')->name('listardetalhe');
			Route::any('buscar/{codigo}', 'NfeController@listar_detalhe_codigo')->name('buscardetalhe');
			Route::any('buscar-form', 'NfeController@listar_detalhe_buscar')->name('buscar');

app/Models/Importador/Cpfvendedor.php
<?php

namespace App\Models\Importador;

use Illuminate\Support\Facades\DB;

class Cpfvendedor
{
	public static function atualizarBase (array $itens)
	{
		foreach ($itens as $item)
		{
			DB::connection('magento')->table('sales_flat_order_origem_pedido')
				->join('sales_flat_order', 'sales_flat_order_origem_pedido.order_id', 'sales_flat_order.entity_id')
				->where('sales_flat_order.increment_id', $item['pedido'])
				->update(['cpf_vendedor_parceiro' => $item['cpf']])
			;
		}
	}
}

app/Models/Importador/DowngradeTim.php
<?php

namespace App\Models\Importador;

use Illuminate\Database\Eloquent\Model;
use App\Models\Importador\Log;
use Auth;

class DowngradeTim extends Model {
    protected $connection 		= 'magento';
	protected $table 			= 'downgrade_tim';
	protected $fillable 		= ['plano_atual', 'plano_destino', 'tipo_movimentacao',];
	public $timestamps 			= false;

	const SUCCESS_MESSAGE 		= 'Importação realizada com sucesso.';
	const FAIL_MESSAGE 			= 'Não foi possível fazer a importação desta planilha.';
	
    public static function criarViaUpload($data) : Array
	{
		$user = Auth::check() ? Auth::user() : null;

		try{
			$contagemInseridos 	= 0;
			$contagemEditados 	= 0;
			$contagemNulos 		= 0;
			$totalItens 		= count($data);
			
			foreach( $data as $item ) {
				$model = self::where('plano_atual',$item['plano_atual'])->where('plano_destino',$item['plano_destino'])->get();

				if( 0 == count($model) ) {
					if( 0 == strlen( $item['tipo_movimentacao'] ) || 0 == strlen( $item['plano_destino'] ) || 0 == strlen( $item['plano_atual'] ) ) {
						$contagemNulos++;
						continue;
					}
					
					
					$contagemInseridos++;
					$plano = [
						'plano_atual' 	=> $item['plano_atual'],
						'plano_destino'	=> $item['plano_destino'],
						'tipo_movimentacao'	=> $item['tipo_movimentacao'],
					];
					
					self::create($plano);
					
					continue;
				}

				foreach( $model as $row ) {
					if( 0 == strlen( $item['tipo_movimentacao'] ) || 0 == strlen( $item['plano_destino'] ) || 0 == strlen( $item['plano_atual'] ) ) {
						$contagemNulos++;
						continue;
					}
					
					if( $row->tipo_movimentacao != $item['tipo_movimentacao'] ) {
						$contagemEditados++;

						$plano = self::find($row->id);
						$plano->tipo_movimentacao = $item['tipo_movimentacao'];
						$plano->save();
					}
				}
			}
		}
		catch( \Exception $e ) {
			Log::logIt( Log::CHANNEL_DOWNGRADE_TIM, self::FAIL_MESSAGE, $e->getMessage(), Log::BAD_REQUEST, Log::LEVEL_ERROR  );

			throw new \Exception(self::FAIL_MESSAGE);
		}
		
		$result = [
			'itens_inseridos' 		=> $contagemInseridos,
			'itens_editados' 		=> $contagemEditados,
			'itens_ignorados' 		=> $contagemNulos,
			'total_importado' 		=> ($contagemInseridos + $contagemEditados),
			'total_itens_planilha' 	=> $totalItens,
			'imported_at' 			=> date('Y-m-d H:i:s'),
			'user'					=> (isset($user->id)) ? ['id' => $user->id, 'login' => $user->login] : '',
		];
		
		Log::logIt( Log::CHANNEL_DOWNGRADE_TIM, self::SUCCESS_MESSAGE, $result );

		return $result;
	}
}
  

app/Models/Importador/DowngradeVivo.php
<?php

namespace App\Models\Importador;

use Illuminate\Database\Eloquent\Model;
use App\Models\Importador\Log;
use Auth;

class DowngradeVivo extends Model {
    protected $connection 		= 'magento';
	protected $table 			= 'downgrade_vivo';
	protected $fillable 		= ['plano_atual', 'plano_destino', 'tipo_movimentacao',];
	public $timestamps 			= false;
	

	const SUCCESS_MESSAGE 		= 'Importação realizada com sucesso.';
	const FAIL_MESSAGE 			= 'Não foi possível fazer a importação desta planilha.';
	
    public static function criarViaUpload($data) : Array
	{
		$user = Auth::check() ? Auth::user() : null;

		try{
			$contagemInseridos 	= 0;
			$contagemEditados 	= 0;
			$contagemNulos 		= 0;
			$totalItens 		= count($data);
			
			foreach( $data as $item ) {
				$model = self::where('plano_atual',$item['plano_atual'])->where('plano_destino',$item['plano_destino'])->get();

				if( 0 == count($model) ) {
					if( 0 == strlen( $item['tipo_movimentacao'] ) || 0 == strlen( $item['plano_destino'] ) || 0 == strlen( $item['plano_atual'] ) ) {
						$contagemNulos++;
						continue;
					}
					
					
					$contagemInseridos++;
					$plano = [
						'plano_atual' 	=> $item['plano_atual'],
						'plano_destino'	=> $item['plano_destino'],
						'tipo_movimentacao'	=> $item['tipo_movimentacao'],
					];
					
					self::create($plano);
					
					continue;
				}

				foreach( $model as $row ) {
					if( 0 == strlen( $item['tipo_movimentacao'] ) || 0 == strlen( $item['plano_destino'] ) || 0 == strlen( $item['plano_atual'] ) ) {
						$contagemNulos++;
						continue;
					}
					
					if( $row->tipo_movimentacao != $item['tipo_movimentacao'] ) {
						$contagemEditados++;

						$plano = self::find($row->id);
						$plano->tipo_movimentacao = $item['tipo_movimentacao'];
						$plano->save();
					}
				}
			}
		}
		catch( \Throwable $e ) {
			Log::logItVivo( Log::CHANNEL_DOWNGRADE_VIVO, self::FAIL_MESSAGE, $e->getMessage(), Log::BAD_REQUEST, Log::LEVEL_ERROR  );

			throw new \Exception($e->getMessage());
		}
		
		$result = [
			'itens_inseridos' 		=> $contagemInseridos,
			'itens_editados' 		=> $contagemEditados,
			'itens_ignorados' 		=> $contagemNulos,
			'total_importado' 		=> ($contagemInseridos + $contagemEditados),
			'total_itens_planilha' 	=> $totalItens,
			'imported_at' 			=> date('Y-m-d H:i:s'),
			'user'					=> (isset($user->id)) ? ['id' => $user->id, 'login' => $user->login] : '',
		];
		
		Log::logItVivo( Log::CHANNEL_DOWNGRADE_VIVO, self::SUCCESS_MESSAGE, $result );

		return $result;
	}
}
  

app/Models/Importador/Exception/CancelUpload.php
<?php

namespace App\Models\Importador\Exception;

class CancelUpload implements \Exception
{
	public $regra;
	public $dado;

	public function __construct ($mensagem, $regra, $dado)
	{
		$this->regra = $regra;
		$this->dado = $dado;

		parent::__construct($mensagem);
	}
}

app/Models/Importador/Exception/RemoveLine.php
<?php

namespace App\Models\Importador\Exception;

class RemoveLine extends \Exception
{
	public $regra;
	public $dado;

	public function __construct ($mensagem, $regra, $dado)
	{
		$this->regra = $regra;
		$this->dado = $dado;

		parent::__construct($mensagem);
	}
}

app/Models/Importador/Log/Importacao.php
<?php

namespace App\Models\Importador\Log;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Importacao extends Model
{
	public $timestamps			= false;
	protected $primaryKey		= 'id';
	protected $table			= 'log';
	protected $connection		= 'importador';
	protected $fillable			= ['data', 'importador', 'usuario', 'arquivo','resultado'];
	
	public function getResultadoAttribute ($valor)
	{
		if (is_null($valor))
			return null;

		return \json_decode(\gzuncompress($valor));
	}

	public function setResultadoAttribute ($valor)
	{
		if (!is_null($valor))
			$valor = \gzcompress(\json_encode($valor));

		$this->attributes['resultado'] = $valor;
	}

	public function clearAndSave ()
	{
		$this->resultado = null;
		Storage::disk('importador')->delete($this->arquivo);

		$this->save();
	}

	public static function getOlderThan (int $timeInDays = 30)
	{
		return self
			::whereNull('resultado')
			->where('data', '<', date('Y-m-d H:i:S', strtotime('-' . $timeInDays . ' days')))
			->get()
		;
	}

	public static function gerar (\App\Models\Importador\Importador $importador, string $arquivo, $inseridos, $removidos)
	{
		return self::create([
			'data'			=> Date('Y-m-d H:i:s'),
			'importador'	=> $importador->id,
			'usuario'		=> @\Auth::user()->id,
			'arquivo'		=> $arquivo,
			'resultado'		=> ['inseridos' => \count($inseridos), 'removidos' => $removidos]
		]);
	}
}

resources/views/importador/downgradeVivo.blade.php
@extends('layouts.admin')

@section('title', 'Importador Downgrade VIVO')
@section('content')

@if(Session::has('message'))
<div class="row">
    <div class="col-md-12">
        <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
    </div>
</div>
@endif

<div class="row">
    <div class="col-md-12">
        <div class="callout callout-success">
            <h4>Selecione um arquivo abaixo para fazer a importação para a tabela de Downgrade da VIVO.</h4>
            <p>Ultima importação realizada em: <b>{{$lastImport}}</b></p>
            @if( $result )
                <p>
                    Total de itens novos inseridos: <b>{{$result['itens_inseridos']}}</b><br>
                    Total de itens editados: <b>{{$result['itens_editados']}}</b><br>
                    Total de itens ignorados: <b>{{$result['itens_ignorados']}}</b><br>
                    Total de itens na planilha: <b>{{$result['total_itens_planilha']}}</b><br>
                    Total de itens importados: <b>{{$result['total_importado']}}</b>
                </p>
            @endif
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="box box-success">
            <div class="box-header with-border">
              <h3 class="box-title">Importar Planilha</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form action="{{route('importador.downgradevivo_send')}}" class="form-horizontal" enctype="multipart/form-data" method="post">
                @csrf
                <div class="box-body">
                    <div class="form-group">
                        <label for="planilha" class="col-sm-2 control-label">Planilha de Importação</label>
                        <div class="col-sm-10">
                            <input type="file" id="planilha" name="planilha" accept=".xlsx, .xls" />
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-danger pull-right"><i class="fa fa-arrow-up"></i> &nbsp; Importar Planilha</button>
                </div>
                <!-- /.box-footer -->
            </form>
        </div>
    </div>
</div>

@endsection

resources/views/importador/downgradetim.blade.php
@extends('layouts.admin')

@section('title', 'Importador Downgrade TIM')
@section('content')

@if(Session::has('message'))
<div class="row">
    <div class="col-md-12">
        <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
    </div>
</div>
@endif

<div class="row">
    <div class="col-md-12">
        <div class="callout callout-success">
            <h4>Selecione um arquivo abaixo para fazer a importação para a tabela de Downgrade da TIM.</h4>
            <p>Ultima importação realizada em: <b>{{$lastImport}}</b></p>
            @if( $result )
                <p>
                    Total de itens novos inseridos: <b>{{$result['itens_inseridos']}}</b><br>
                    Total de itens editados: <b>{{$result['itens_editados']}}</b><br>
                    Total de itens ignorados: <b>{{$result['itens_ignorados']}}</b><br>
                    Total de itens na planilha: <b>{{$result['total_itens_planilha']}}</b><br>
                    Total de itens importados: <b>{{$result['total_importado']}}</b>
                </p>
            @endif
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="box box-success">
            <div class="box-header with-border">
              <h3 class="box-title">Importar Planilha</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form action="{{route('importador.downgradetim_send')}}" class="form-horizontal" enctype="multipart/form-data" method="post">
                @csrf
                <div class="box-body">
                    <div class="form-group">
                        <label for="planilha" class="col-sm-2 control-label">Planilha de Importação</label>
                        <div class="col-sm-10">
                            <input type="file" id="planilha" name="planilha" accept=".xlsx, .xls" />
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-danger pull-right"><i class="fa fa-arrow-up"></i> &nbsp; Importar Planilha</button>
                </div>
                <!-- /.box-footer -->
            </form>
        </div>
    </div>
</div>

@endsection

resources/views/importador/importar.blade.php
@extends('layouts.admin')

@section('title', 'Importar Arquivo: ' . @$importador->layout->nome)

@push('header.css')

<style type="text/css">

	.limited-text-content {
		max-width:100%;
		overflow:hidden;
		text-overflow:ellipsis;
		white-space:nowrap;
	}

</style>

@endpush

@section('content')

<form class="row" method="post" action="{{route('importador.importar', [$importador->id])}}" enctype="multipart/form-data">
	<div class="col-md-12">
		@csrf
		<div class="box box-info">
			
			<div class="form-horizontal">
				<div class="box-body">

					@switch (@$importador->regras->obter->tipo)

						@case('file_upload')

						<div class="form-group">
							<label for="nota" class="col-sm-2 control-label">Arquivo</label>
							<div class="col-sm-10">
								<input type="file" name="file" accept="{{@$importador->regras->obter->arquivo->accept}}" required />
								<p class="help-block">{{@$importador->regras->obter->arquivo->descricao}}</p>
							</div>
						</div>

						@break

					@endswitch
				
				</div>
				<div class="box-footer">
					<div class="row">
						<div class="col-md-10 col-md-offset-2">
							<a class="btn btn-default" href="{{route('importador.importar')}}">Cancelar Importação</a>
							<button type="submit" class="btn btn-info pull-right">Importar Arquivo</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>

@endsection

resources/views/importador/statuspedido.blade.php
@extends('layouts.admin')

@section('title', 'Importador Status Pedido')
@section('content')

@if(Session::has('message'))
<div class="row">
    <div class="col-md-12">
        <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
    </div>
</div>
@endif

<div class="row">
    <div class="col-md-12">
        <div class="callout callout-success">
            <h4>Selecione um arquivo abaixo para fazer a importação e alterar Status e Data da Ativação de pedidos.</h4>
            @if( $result )
                <p>
                    Total de pedidos editados: <b>{{$result['total_itens_editados']}}</b><br>
                    Total de pedidos ignorados: <b>{{$result['total_itens_ignorados']}}</b><br>
                    Total de pedidos na planilha: <b>{{$result['total_itens_planilha']}}</b>
                </p>
            @endif
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <form action="{{route('importador.downloadplanilha')}}" class="form-horizontal" enctype="multipart/form-data" method="get">
            <button class="btn btn-primary pull-right" style="font-weight: bolder">
                <i class="fa fa-arrow-down"></i> &nbsp; FAZER DOWNLOAD DO MODELO DA PLANILHA!
            </button>
        </form>
    </div>
</div>

<br />

<div class="row">
    <div class="col-md-12">
        <div class="box box-success">
            <div class="box-header with-border">
                <h3 class="box-title">Importar Planilha</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form action="{{route('importador.statuspedido')}}" class="form-horizontal" enctype="multipart/form-data" method="post">
                @csrf
                <div class="box-body">
                    <div class="form-group">
                        <label for="planilha" class="col-sm-2 control-label">Planilha de Importação</label>
                        <div class="col-sm-10">
                            <input type="file" id="planilha" name="planilha" accept=".xlsx, .xls" />
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <button type="submit" class="btn btn-danger pull-right"><i class="fa fa-arrow-up"></i> &nbsp; Importar Planilha</button>
                </div>
                <!-- /.box-footer -->
            </form>
        </div>
    </div>
</div>

@endsection