routes/web.php
		// Route::any('/remuneracao/editar/{id}', 'TabelaController@remuneracao_editar')->name('remuneracao.editar');
		// Route::any('/remuneracao/deletar/{id}', 'TabelaController@remuneracao_deletar')->name('remuneracao.deletar');

	});

	Route::middleware('permissao:contestador.admin')->group(function () {

		Route::any('/config', 'ConfigController@geral')->name('config');

	});

});

/**
 * Catálogo
 */
 Route::namespace('Catalogo')->prefix('/catalogo')->name('catalogo.')->middleware('permissao:catalogo')->group(function () {

	Route::prefix('/contingencia')->name('contingencia.')->middleware('permissao:catalogo.contingencia')->group(function () {

		Route::any('/analisador-bundle', 'ContingenciaController@analizador_bundle')->name('analisador');

	});

});

/**
 * Alarmística
 */

/**
 * endpoint para o robo do Callel
*/
Route::get('dashboard-robo-acesso', 'Alarmistica\ApiController@listaLogs');


Route::namespace('Alarmistica')->prefix('/alarmistica')->middleware('permissao:alarmistica')->name('alarmistica.')->group(function () {

	Route::prefix('/api')->name('api.')->group(function () {

		Route::get('exibeIndicadoresMenu', 'ApiController@exibeIndicadoresMenu')->name('exibeIndicadoresMenu');
		Route::any('listaApis', 'ApiController@listaApis')->name('listaApis');
		Route::any('listaLogs', 'ApiController@listaLogs')->name('listaLogs');
		
	});

	Route::middleware('permissao:alarmistica.admin')->group(function () {

		Route::prefix('/configuracao')->name('configuracao.')->group(function () {
			route::any('/ajustar', 'ConfiguracaoController@ajustar')->name('ajustar');
			route::any('/editar', 'ConfiguracaoController@editar')->name('editar');
			route::any('/cadastro', 'ConfiguracaoController@cadastro')->name('cadastro');
			route::any('/alterar', 'ConfiguracaoController@alterar')->name('alterar');
		});
	});

	Route::get('backlog', 'ApiController@backlog')->name('backlog');
	Route::post('/backlog-importar','ApiController@backlogImportar')->name('backlog_send');
});

/**
 * Indicadores
 */

 Route::namespace('Indicadores')->prefix('/indicadores')->middleware('permissao:indicadores')->name('indicadores.')->group(function () {

	Route::get('/logistica-consolidado','LogisticaController@consolidado')->name('logisticaconsolidado');

	Route::prefix('/graficosindicadores')->name('graficosindicadores.')->group(function(){
		route::get('/index', 'GraficosIndicadoresController@index')->name('index');
		route::get('/cadastrarMetas', 'GraficosIndicadoresController@cadastrarMetas')->name('cadastrarMetas');
	});

});

/**
 * Reaproveitamento
 */
Route::namespace('Reaproveitamento')->prefix('/reaproveitamento')->middleware('permissao:reaproveitamento')->name('reaproveitamento.')->group(function () {
	Route::get('/agendar_reaproveitamento','ReaproveitamentoController@AgendarReaproveitamento')->name('agendar_reaproveitamento');
	Route::post('/reaproveitamento.salvar_agendamento','ReaproveitamentoController@SalvarAgendamento')->name('salvar_agendamento');
	Route::post('/reaproveitamento.excluir_agendamento','ReaproveitamentoController@ExcluirAgendamento')->name('excluir_agendamento');
});

/**
 * Filas
 */
Route::namespace('Filas')->prefix('/filas')->name('filas.')->group(function () {
	Route::any('/gravar_pedido_fila/{fila}/{pedido}', 'FilasMagentoController@GravarPedidoFila')->name('gravar_pedido_fila');
});

/**
 * Pós-venda
 */
Route::namespace('Posvenda')->prefix('/posvenda')->middleware('permissao:posvenda')->name('posvenda.')->group(function () {
	Route::get('/registrar_atendimentos','PosVendaController@registrarAtendimentos')->name('registrar_atendimentos');
	Route::any('/listar_atendimentos','PosVendaController@listarAtendimentos')->name('listar_atendimentos');
	Route::post('/atendimentos.salvar','PosVendaController@salvarAtendimento')->name('salvar_atendimento');
	Route::post('/aviso.salvar','PosVendaController@salvarAviso')->name('salvar_aviso');
	Route::get('/buscar_motivos/{id?}','PosVendaController@buscarMotivos')->name('buscar-motivos');
	Route::get('/buscar_atendimento_por_motivo', 'PosVendaController@buscarAtendimentoPorPedido')->name('buscar-por-pedido');
	Route::get('/search_mortivos/{id?}','PosVendaController@seachMotivos')->name('search-motivos');
	Route::get('/busca_comentarios/{id?}','PosVendaController@buscarComentarios')->name('buscar-comentarios');
	Route::get('/busca_origens','PosVendaController@buscarOrigens')->name('buscar-origens');
	
	Route::middleware('permissao:posvenda.admin')->group(function () {
		Route::get('/deletar-atendimento/{id?}','PosVendaController@deletarAtendimento')->name("posvenda.deletar");
		Route::get('/adicionar_opcoes','PosVendaController@adicionarOpcoes')->name('adicionar_opcoes');
		Route::get('/alterar_opcoes','PosVendaController@alterarOpcoes')->name('alterar_opcoes');
		Route::get('/status','PosVendaController@buscarStatus');
		Route::any('/administrar_relacoes_motivos/{id?}','PosVendaController@administrarRelacoesMotivos')->name('administrar_relacoes_motivos');
		Route::get('/listar_motivos','PosVendaController@listarMotivos')->name('listar_motivos');
		Route::post('/atendimentos.salvar_opcoes','PosVendaController@salvarOpcoes')->name('salvar_opcoes');
		Route::post('/atendimentos.salvar_alterar_opcoes','PosVendaController@salvarAlterarOpcoes')->name('salvar_alterar_opcoes');
		Route::post('/cadastrar','PosVendaController@cadastrarAtendimento')->name('posvenda.cadastrar');
	});
});

/**
 * Magento
 */

Route::prefix('/magento')->namespace('Magento')->name('magento.')->group(function () {

	Route::any('vincular-login-magento', 'LoginController@vincular')->name('vincular');

	Route::any('alterar-dia-vencimento', 'PedidoController@dia_vencimento')->name('dia_vencimento');
	Route::any('atualizar-nomenclatura-sap', 'PedidoController@atualizar_nomenclatura')->name('nomenclaturasap');

	Route::any('/pedidos', 'PedidoController@listar')->name('pedido.listar');
	Route::any('/pedidos/ver/{pedido}', 'PedidoController@ver')->name('pedido.ver');

	Route::any('status-motivos-listar', 'MotivoController@listar')->name('motivos.listar');
	Route::any('status-motivos-criar', 'MotivoController@criar')->name('motivos.criar');
	Route::any('admin-user-base-listar', 'AdminUserBaseController@listar')->name('adminuser.listar');
	Route::any('admin-user-base-criar', 'AdminUserBaseController@criar')->name('adminuser.criar');
	
	Route::any('json-api-tim/{engine}/{versao}/{json}/{pedido}/{simulation?}', 'PedidoController@get_json_api_tim')
		->where([
			'engine' => 'cubo|tim',
			'versao' => 'v(3|5)',
			'json' => 'elegibilidade|order',
			'simulation' => 'avera']
		)
		->name('pedido.jsonapi')
	;

});

/**
 * Importador
 */

Route::namespace('Importador')->prefix('/importador')->middleware('permissao:importador')->name('importador.')->group(function () {

	Route::any('/importar/{id?}', 'ImportadorController@importar')->name('importar');

	Route::middleware('permissao:importador.downgrade')->group(function () {
		Route::get('/downgrade-tim-importar','ImportadorController@downgradeTimImportar')->name('downgradetim');
		Route::post('/downgrade-tim-importar','ImportadorController@downgradeTimImportar')->name('downgradetim_send');
		Route::get('/downgrade-vivo-importar','ImportadorController@downgradeVivoImportar')->name('downgradeVivo');
		Route::post('/downgrade-vivo-importar','ImportadorController@downgradeVivoImportar')->name('downgradevivo_send');
		Route::get('/downgrade-listar','ImportadorController@listar')->name('downgrade-listar');
	});
	
	Route::middleware('permissao:importador')->group(function () {
		Route::any('/status-pedido-importar','ImportadorController@statusPedidoImportar')->name('statuspedido');
		Route::get('/download-modelo-planilha', 'ImportadorController@downloadModeloPlanilha')->name('downloadplanilha');
		Route::any('/varejo-loja','ImportadorController@importarVarejoLoja')->name('varejoloja');
		Route::any('/cpf-vendedor','ImportadorController@cpf_vendedor')->name('cpfvendedor');
		Route::any('/phone-number','ImportadorController@phone_number')->name('phonenumber');
		Route::any('/decriptador-pedidos','ImportadorController@decrypt')->name('decrypt');
	});
});

/**
 * retornos
 */
Route::namespace('Retornos')->prefix('/retornos')->middleware('permissao:robo.retornos')->name('retornos.')->group(function () {
	Route::prefix('/tim')->namespace('Tim')->name('tim.')->group(function () {
		Route::get('/consulta-ordem','HistoricoController@consultaOrdem')->name('historicos.consultaordem');
	});
});

Route::namespace("Lojaonline")->prefix('/lojaonline')->name('lojaonline.')->group(function () {

	Route::any('enviar-pedidos-email', function () {
		Artisan::call('lojaonline:relatorio_crivo');
		return 'Enviado!';
	});

	Route::any('/api/claro/{data_inicio}/{data_fim}', 'ApiController@pedidos_claro')->name('pedidos.claro');
	Route::any('/api/claro_prospect/{data_inicio}/{data_fim}', 'ApiController@pedidos_claro_prospect')->name('pedidos.claro_prospect');
	Route::any('/api/claro_pre/{data_inicio}/{data_fim}', 'ApiController@pedidos_claro_pre')->name('pedidos.claro_pre');
	Route::any('/api/claro_pos/{data_inicio}/{data_fim}', 'ApiController@pedidos_claro_pos')->name('pedidos.claro_pos');

	Route::any('/pedidos/{loja}', 'PedidosController@listar')->name('pedidos.listar');

});

/**
 * Colmeia
 */

###############################
#suporte rotas antigas
###############################

#Route::any('/lista-colmeia','Colmeia\ArmarioController@lista');
Route::get('/busca-chip-estoque/{serial}', 'Colmeia\Api\v1\ProdutoController@check_serial_exists');
Route::get('/api-picking-automatico/{serial?}/{sku?}', 'Colmeia\Api\v1\ProdutoController@check_picking');
Route::get('/liberar-chip-colmeia/{nota}/{pedido}/{serial}/{sku}/{imei?}', 'Colmeia\Api\v1\ProdutoController@liberar_chip');
Route::get('/liberar-aparelho-colmeia/{nota}/{pedido}/{imei}', 'Colmeia\Api\v1\ProdutoController@liberar_aparelho');
Route::get('/retorna-sku/{serial}','ProdutoController@busca_sku');

app/Models/Posvenda/Acao.php
<?php

namespace App\Models\Posvenda;

use Illuminate\Database\Eloquent\Model;

class Acao extends Model {

	#Configuração padrão do Eloquent para definição de qual tabela do banco de dados e qual conexão será usada para gerenciar esse model
	protected $table			= 'acao';
	protected $connection		= 'posvenda';
	public $timestamps 			= false;

	const ACAO_CANCELAR_PEDIDO 	= 44;
	const ACAO_STATUS_MOTIVO 	= 33;
	
}

app/Models/Posvenda/Atendimentos.php
<?php

namespace App\Models\Posvenda;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Atendimentos extends Model {

	#Configuração padrão do Eloquent para definição de qual tabela do banco de dados e qual conexão será usada para gerenciar esse model
	protected $table			= 'atendimentos';
	protected $connection		= 'posvenda';
	
	public function proximoProtocolo() {
		return str_pad(intval($this->latest()->first()->protocolo)+1, 10, '0', STR_PAD_LEFT);
	}

	public function salvarAtendimento( $objeto ) {
		try {
			$cpf = $objeto->input('cpf');
			$cpf = preg_replace('/[,.\-\/]/m', '', trim($cpf));
			
			$this->protocolo 			= $this->proximoProtocolo();
			$this->id_origem 			= $objeto->input('origem');
			$this->id_canal_atendimento = $objeto->input('canal');
			$this->id_operadora_produto = $objeto->input('operadora');
			$this->id_atendimento 		= $objeto->input('id_atendimento');
			$this->nome_cliente 		= $objeto->input('nome_cliente');
			$this->id_motivo1 			= $objeto->input('motivo1');
			$this->id_motivo2 			= $objeto->input('motivo2');
			$this->id_acao 				= $objeto->input('acao');
			$this->chamado 				= $objeto->input('chamado');
			$this->id_usuario 			= \Auth::user()->id;
			$this->numero_pedido 		= (true === $objeto->check_cliente) 	? 'Não Cliente' 	: $objeto->input('pedido');
			$this->cpf_cliente 			= (true === $objeto->check_cpf) 		? 'Não Informado' 	: $cpf;
			$this->numero_telefone 		= (true === $objeto->check_telefone) 	? 'Não Informado' 	: $objeto->input('telefone');
			$this->email 				= (true === $objeto->check_email) 		? 'Não Informado' 	: $objeto->input('email');
			$this->save();
		}
		catch( \Throwable $exception ) {
			throw new \Exception($exception->getMessage());
		}
		
		return $this;
	}

	public function listarAtendimentos($filtros) {
		$db_usuario = env("CONNECTION_HUB_DATABASE", 'hub');
		$dados = $this
					->select(DB::raw('date_format(created_at, "%d/%m/%Y %H:%i:%s") as data'), 'atendimentos.id','protocolo', 'id_atendimento', 'origem.origem', 'canal_atendimento.canal_atendimento','operadora_produto.operadora_produto',
					'motivo1.motivo as motivo1', 'motivo2.motivo as motivo2', 'acao.acao', 'numero_pedido', 'nome_cliente', 'cpf_cliente', 'numero_telefone', 'email', 'chamado', $db_usuario.'.usuario.nome')
						->leftJoin('origem', 'id_origem', 'origem.id')
						->leftJoin('canal_atendimento', 'id_canal_atendimento', 'canal_atendimento.id')
						->leftJoin('operadora_produto', 'id_operadora_produto', 'operadora_produto.id')
						->leftJoin('motivo1', 'id_motivo1', 'motivo1.id')
						->leftJoin('motivo2', 'id_motivo2', 'motivo2.id')
						->leftJoin('acao', 'id_acao', 'acao.id')
						->leftJoin($db_usuario.'.usuario', 'id_usuario', $db_usuario.'.usuario.id');

		if (\Auth::user()->checkPermissao('posvenda.claro')) {
			$dados = $dados->where('operadora_produto.operadora_produto', 'Claro');
		}

		if ($filtros->periodo) {
			$periodo = explode(" - ", $filtros->periodo);
			$inicio = explode("/", $periodo[0]);
			$fim = explode("/", $periodo[1]);
			$dados = $dados->whereBetween('created_at', [$inicio[2].'-'.$inicio[1].'-'.$inicio[0], $fim[2].'-'.$fim[1].'-'.$fim[0]]);
		}
		
		if ($filtros->protocolo) {
			$dados = $dados->where('protocolo', $filtros->protocolo);
		}

		if ($filtros->id_atendimento) {
			$dados = $dados->where('id_atendimento', $filtros->id_atendimento);
		}

		if ($filtros->origem) {
			$dados = $dados->where('id_origem', $filtros->origem);
		}

		if ($filtros->canal_atendimento) {
			$dados = $dados->where('id_canal_atendimento', $filtros->canal_atendimento);
		}

		if ($filtros->operadora_produto) {
			$dados = $dados->where('id_operadora_produto', $filtros->operadora_produto);
		}

		if ($filtros->numero_pedido) {
			$dados = $dados->where('numero_pedido', $filtros->numero_pedido);
		}

		if ($filtros->nome_cliente) {
			$dados = $dados->where('nome_cliente', $filtros->nome_cliente);
		}

		if ($filtros->cpf_cliente) {
			$dados = $dados->where('cpf_cliente', $filtros->cpf_cliente);
		}

		if ($filtros->motivo1) {
			$dados = $dados->where('id_motivo1', $filtros->motivo1);
		}

		if ($filtros->motivo2) {
			$dados = $dados->where('id_motivo2', $filtros->motivo2);
		}

		if ($filtros->acao) {
			$dados = $dados->where('id_acao', $filtros->acao);
		}

		if ($filtros->usuario) {
			$dados = $dados->where('nome', 'like', '%'.$filtros->usuario.'%');
		}
		
		return $dados->orderByDesc('created_at');
	}

	/**
	 * Custom Scopes
	 */

	public function scopeSomenteClaro ($query)
	{
		return $query->whereHas('operadora', function ($query) {
			$query->where('operadora_produto', 'Claro');
		});
	}

	public function scopeFiltroListaAtendimento ($query, $filtros)
	{
		if (isset($filtros['periodo']))
		{
			$periodo = explode(" - ", $filtros['periodo']);
			$inicio = explode("/", $periodo[0]);
			$fim = explode("/", $periodo[1]);
			$query->whereBetween('created_at', [$inicio[2].'-'.$inicio[1].'-'.$inicio[0], $fim[2].'-'.$fim[1].'-'.$fim[0]]);
		}
		
		if (isset($filtros['protocolo']))
		{
			$query->where('protocolo', $filtros['protocolo']);
		}

		if (isset($filtros['id_atendimento']))
		{
			$query->where('id_atendimento', $filtros['id_atendimento']);
		}

		if (isset($filtros['origem']))
		{
			$query->where('id_origem', $filtros['origem']);
		}

		if (isset($filtros['canal_atendimento']))
		{
			$query->where('id_canal_atendimento', $filtros['canal_atendimento']);
		}

		if (isset($filtros['operadora_produto']))
		{
			$query->where('id_operadora_produto', $filtros['operadora_produto']);
		}

		if (isset($filtros['numero_pedido']))
		{
			$query->where('numero_pedido', $filtros['numero_pedido']);
		}

		if (isset($filtros['nome_cliente']))
		{
			$query->where('nome_cliente', $filtros['nome_cliente']);
		}

		if (isset($filtros['cpf_cliente']))
		{
			$query->where('cpf_cliente', $filtros['cpf_cliente']);
		}

		if (isset($filtros['motivo1']))
		{
			$query->where('id_motivo1', $filtros['motivo1']);
		}

		if (isset($filtros['motivo2']))
		{
			$query->where('id_motivo2', $filtros['motivo2']);
		}

		if (isset($filtros['acao']))
		{
			$query->where('id_acao', $filtros['acao']);
		}

		if (isset($filtros['usuario']))
		{
			$usuario = $filtros['usuario'];

			$query->whereHas('usuario', function ($query) use ($usuario) {
				$query->where('nome', 'like', '%' . $usuario . '%');
			});
		}

		return $query;
	}

	/**
	 * Relationship
	 */

	public function usuario ()
	{
		return $this->belongsTo(\App\Models\User::class, 'id_usuario')->withTrashed();
	}

	public function acao ()
	{
		return $this->belongsTo(\App\Models\Posvenda\Acao::class, 'id_acao');
	}

	public function motivo1 ()
	{
		return $this->belongsTo(\App\Models\Posvenda\Motivo1::class, 'id_motivo1');
	}

	public function motivo2 ()
	{
		return $this->belongsTo(\App\Models\Posvenda\Motivo2::class, 'id_motivo2');
	}

	public function origem ()
	{
		return $this->belongsTo(\App\Models\Posvenda\Origem::class, 'id_origem');
	}

	public function canal ()
	{
		return $this->belongsTo(\App\Models\Posvenda\CanalAtendimento::class, 'id_canal_atendimento');
	}

	public function operadora ()
	{
		return $this->belongsTo(\App\Models\Posvenda\OperadoraProduto::class, 'id_operadora_produto');
	}
}

resources/views/posvenda/adicionar_opcoes.blade.php
@extends('layouts.admin')

@section('title', 'Adicionar Opções')

@push('header.javascript')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js"></script>
    <script>
        $(function() {
            $("#form").validate({
                rules: {
                    campo: "required",
                    valor: "required"
                }
            });
        });
    </script>
@endpush
@push('header.css')
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css' />
    <style type="text/css">
        label.error {
            display: none !important;
        }
        .form-control.error {
            border-color: red !important;
        }
        .w-100 {
            width: 100%;
        }
    </style>
@endpush

@section('content')

@if(Session::has('message'))
<div class="row">
    <div class="col-md-12">
        <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
    </div>
</div>
@endif

@if ($s)
<div class="row">
    <div class="col-md-12">
        <div class="callout callout-success">
            <p><b>Registro salvo com sucesso</b></p>
        </div>
    </div>
</div>
@endif

<div class="row">
    <div class="col-md-12">
        <div class="box box-success">
            <form action="{{route('posvenda.salvar_opcoes')}}" class="form-horizontal" enctype="multipart/form-data" method="post" id='form'>
                @csrf
                <div class="box-body">
                    <div class="form-group">
                        <div class="col-md-4">
                            <label class="control-label">Campo</label>
                            <select class="form-control" name='campo' id='campo'>
                                <option value="">Selecione</option>
                                <option value="origem">Origem</option>
                                <option value="canal_atendimento">Canal de Atendimento</option>
                                <option value="operadora_produto">Operadora/ Produto</option>
                                <option value="motivo1">Motivo de Contato</option>
                                <option value="motivo2_label">Motivo de Contato 2</option>
                                <option value="acoes">Ação</option>
                            </select>
                        </div>
                        <div class="col-md-8 w-100"></div>
                        <div class="col-md-4 campo_texto" id='texto'>
                            <label class="control-label">Valor</label>
                            <input class="form-control" type="text" id='valor' name='valor' />
                        </div>
                    </div>
                </div>
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary"><i class="fa fa-floppy-o"></i>&nbsp;Salvar</button>
                </div>
            </form>
        </div>
    </div>
</div>

@endsection

resources/views/posvenda/listar_motivos.blade.php
@extends('layouts.admin')

@section('title', 'Administrar Motivos')

@push('header.css')

<style type="text/css">

	.limited-text-content {
		max-width:100%;
		overflow:hidden;
		text-overflow:ellipsis;
		white-space:nowrap;
	}

</style>

@endpush

@section('content')

<div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Lista de Motivos</h3>
                </div>
                <div class="box-body">
                        
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th width="5%">Ação</th>
                                <th>Id</th>
                                <th>Motivo</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        @if($dados)
                        <tbody>
                            @foreach($dados as $model)
                                <tr>
                                    <td><a href="{{route('posvenda.administrar_relacoes_motivos')}}/{{ $model->id }}" class="btn btn-warning btn-sm"><i class="fa fa-cog"></i></button></td>
                                    <td>{{ $model->id }}</td>
                                    <td>{{ $model->motivo }}</td>
                                    <td>{{ ($model->status) ? 'Habilitado' : 'Desabilitado' }}</td>
                                </tr>
                            @endforeach
                        </tbody>
                        @endif
                    </table>
                </div>
            </div>
        </div>
</div>

@endsection